name: Latest Blog Post Workflow

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Pull in dev.to/medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/rahulkumargit1,https://medium.com/feed/@rahulkumargit1"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Updated with latest blog posts [skip ci]"
